### ISSUE TITLE
why not support for cpu cluster?

### ISSUE THREAD

**Issue by banbanandroid** [AliyunContainerService/arena#3] opened 2018-08-06 06:51 UTC
I dont't have a gpu cluster but cpu, and why not support for cpu cluster?

**Comment by cheyang** [comment] 2018-08-06 08:05
It can also support cpu cluster. You don't have to specify `--gpu` when you don't need GPU.

**Comment by xiechengsheng** [comment] 2018-08-06 12:56
But in cpu cluster we couldn't see any cpu information(total/allocated) in `top` command :scream:

**Comment by cheyang** [comment] 2018-08-07 00:56
Thanks for reporting it. It will support later. And your contributions are also welcome!

**Comment by xiechengsheng** [comment] 2018-08-07 08:38
Hi @cheyang , I have deployed arena successfully on my small cpu cluster, but the `tf-job` always failed on my cluster, here is the reproduce step:
```
1. check the cluster status
# ./arena top node
INFO[0000] Use specified kubeconfig file /etc/kubernetes/admin.conf 
NAME      IPADDRESS     ROLE    GPU(Total)  GPU(Allocated)
k8s-mst   192.168.1.60  master  0           0
k8s-nod1  192.168.1.61  worker  0           0
k8s-nod2  192.168.1.62  worker  0           0

2. run one tf job
# ./arena submit tf --name=tf-git5 --image=tensorflow/tensorflow:1.5.0-devel --syncMode=git --syncSource=https://github.com/cheyang/tensorflow-sample-code.git "python code/tensorflow-sample-code/tfjob/docker/mnist/main.py --max_steps 10000"
INFO[0000] Use specified kubeconfig file /etc/kubernetes/admin.conf 

NAME:   tf-git5
LAST DEPLOYED: Tue Aug  7 16:31:56 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1alpha2/TFJob
NAME           AGE
tf-git5-tfjob  0s

3. check the job status
./arena get tf-git5
INFO[0000] Use specified kubeconfig file /etc/kubernetes/admin.conf 
NAME     STATUS  TRAINER  AGE  INSTANCE                NODE
tf-git5  FAILED  TFJOB    0s   tf-git5-tfjob-worker-0  N/A

4. can't see the detailed logs because the pod status is failed.
# ./arena logs tf-git5
INFO[0000] Use specified kubeconfig file /etc/kubernetes/admin.conf 
pod 'tf-git5-tfjob-worker-0' has not been started.

```
5. it seems that arena hasn't implemented describe command yet, so I can't get concrete failing reason. :cry:
I don't konw how to solve this probelm, any help will be appreciated!

**Comment by cheyang** [comment] 2018-08-07 09:12
Try `kubectl describe po tf-git5-tfjob-worker-0` to see why the pod is not started successfully.

**Comment by cheyang** [comment] 2018-08-07 13:16
I guess it's failed to download source code from git.

```
State:          Terminated
      Reason:       Error
      Exit Code:    1
```

You can check logs by using `kubectl logs tf-git5 -c init-code`.

**Comment by banbanandroid** [comment] 2018-08-08 08:12
I have the same problem as @xiechengsheng , my k8s version is 1.11.0. 

```
# kubectl get po -n default

NAME                    READY     STATUS       RESTARTS   AGE
tf-git-tfjob-worker-0   0/1       Init:Error   0          41m
```
```
# arena get tf-git

NAME    STATUS  TRAINER  AGE  INSTANCE               NODE
tf-git  FAILED  TFJOB    0s   tf-git-tfjob-worker-0  N/A
```
But later I deployed arena on [playground](https://www.katacoda.com/courses/kubernetes/playground) and it worked fine! The only difference is that the playground's k8s version is 1.10.0, and maybe the network of the playground is better than my cluster?

**Comment by banbanandroid** [comment] 2018-08-08 08:15
It seems the reason failing to download source code from git is right 😢
```
# kubectl logs tf-git-tfjob-worker-0 -c init-code -n default
I0808 07:18:17.469610   32274 main.go:164] starting up: ["/git-sync"]
E0808 07:29:46.803093   32274 main.go:171] error syncing repo: error running command: exit status 128: "Cloning into '/code'...\nerror: RPC failed; curl 18 transfer closed with outstanding read data remaining\nfatal: The remote end hung up unexpectedly\nfatal: early EOF\nfatal: index-pack failed\n"
```

**Comment by cheyang** [comment] 2018-08-08 09:58
Looks like it's connection issue between your machine and github.com. You can try https://www.katacoda.com/courses/kubernetes/playground  . I think there will be no connection issue.

**Comment by xiechengsheng** [comment] 2018-08-08 10:16
Yes, after fixing my kube-dns component problem, tf job runs successfully, thanks!

**Comment by cheyang** [comment] 2018-08-08 11:37
Ok, I will close this issue first, and track with #5

**Closed by cheyang** 2018-08-08 11:37 UTC
